name: SuperSimpleFly
version: 1.0.0
api-version: 1.8.8
author: Bearless
main: fr.bearless.supersimplefly.Main

commands:
  fly:
    description: Allow players to fly
  ssf-reload:
    description: Reload the configuration file